name: Docker Automated Builds

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker build -t godsings .
      - name: Tag
        run: |
          docker tag godsings orhunp/godsings:latest
          docker tag godsings docker.pkg.github.com/orhun/godsings/godsings:latest
      - name: Login (Docker Hub)
        run: echo ${{ secrets.DOCKERHUB_PASS }} |
          docker login -u orhunp --password-stdin
      - name: Push (Docker Hub)
        run: docker push orhunp/godsings:latest
      - name: Login (Package Registry)
        run: echo ${{ secrets.GITHUB_TOKEN }} |
          docker login -u orhun docker.pkg.github.com --password-stdin
      - name: Push (Package Registry)
        run: docker push docker.pkg.github.com/orhun/godsings/godsings:latest
